logging:
  level:
    org:
      springframework: info

management:
  endpoints:
    web:
      exposure:
        include: inf0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    showSql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


