logging:
  level:
    org:
      springframework: info
server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: inf0

spring:
  profiles:
    active: local
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/college
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    showSql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect




